-- top 3 design_names for each quarter (most popular design for each quarter)
-- units sold * sales price for each day of the week (which day of the week would make the most sales)
-- agreed delivery location city 