name: lambda-deployment

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    
    name: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Python Setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Make
        run: sudo apt install make -y
      - name: Run Tests
        run: make all

  deploy-lambda:
    name: deploy-lambda
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: AWS Creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        working-directory: terraform
        run: terraform init
      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan
      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve
            
